name: mirror

on:
  workflow_dispatch:
    inputs:
      name:
        description: Full image name (tag included)
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: base
          build-args: |
            IMAGE=alpine:3.19
          tags: |
            ghcr.io/fopinappb/dockerhub-mirror/alpine:3.19
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: placeholder
        run: |
            echo "### New Version" >> $GITHUB_STEP_SUMMARY
            echo placeholder >> $GITHUB_STEP_SUMMARY
